import * as __SNOWPACK_ENV__ from '../_snowpack/env.js';
import.meta.env = __SNOWPACK_ENV__;

// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "../_snowpack/pkg/react.js";
import * as PostFeed from "./PostFeed.bs.js";
import * as ReactDom from "../_snowpack/pkg/react-dom.js";

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react mount element");
} else {
  ReactDom.render(React.createElement(PostFeed.make, {}), root);
}

if (undefined /* [snowpack] import.meta.hot */ ) {
  undefined /* [snowpack] import.meta.hot */ .accept();
}

export {
  
}
/* root Not a pure module */
